version: "2"

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - misspell
    - gocritic

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/thiagomarinho/joca
